version: "3.7"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static-root:/var/www/static:ro

  mysql:
    image: mysql
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=waggle"
      - "MYSQL_DATABASE=waggle"
    healthcheck:
      test: mysql waggle --user=root --password=waggle --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: manifest-api
    image: manifest-api
    restart: always
    command: gunicorn DjangoManifest.wsgi:application --bind 0.0.0.0:80 --reload
    volumes:
      - ${PWD}/api/:/app:ro
      - static-root:/var/www/static:rw
    environment:
      # Django settings
      - "DJANGO_SETTINGS_MODULE=DjangoManifest.settings.prod"
      - "SECRET_KEY=django-insecure-4DQhs101FK4NgF_PHyEDFyDTze4REhtcHmKiksqO_ztM7vV3Vw"
      - "ALLOWED_HOSTS=localhost 127.0.0.1"
      - "CSRF_TRUSTED_ORIGINS=http://localhost http://127.0.0.1"
      - "DATABASE_BACKEND=django.db.backends.mysql"
      - "DATABASE_HOST=mysql"
      # NOTE(sean) we use the root user to allow django to setup / teardown test databases.
      - "DATABASE_USER=root"
      - "DATABASE_PASSWORD=waggle"
      - "DATABASE_NAME=waggle"

volumes:
  static-root:
