version: "3.7"
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 127.0.0.1:8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static-root:/var/www/static:ro

  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: manifest-api
    image: manifest-api
    restart: always
    command: gunicorn DjangoManifest.wsgi:application --bind 0.0.0.0:80 --reload
    volumes:
      - ${PWD}/api/:/app/
      - static-root:/var/www/static:rw
    environment:
      - "DJANGO_SETTINGS_MODULE=config.settings.prod"
      - SQL_ENGINE
      - DATABASE_BACKEND
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_NAME
      - DEBUG
      - DJANGO_ALLOWED_HOSTS
      - API_PORT
    depends_on:
        postgres:
          condition: service_healthy
    ports:
      - $API_PORT:$API_PORT

  postgres:
    image: postgres:13.3-alpine
    container_name: manifest-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ${PWD}/db/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - ADMIN_USERNAME
      - ADMIN_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      timeout: 20s
      retries: 10

volumes:
  postgres_data:
  static-root:
