# Generated by Django 4.1.1 on 2022-09-22 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VSN', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('gps_lat', models.FloatField()),
                ('gps_lan', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cname', models.CharField(max_length=30)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeviceManifest.nodedata')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cname', models.CharField(max_length=30)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeviceManifest.nodedata')),
            ],
        ),
        migrations.CreateModel(
            name='Compute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cname', models.CharField(max_length=30)),
                ('hardware_id', models.CharField(max_length=30)),
                ('zone', models.CharField(max_length=30)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DeviceManifest.nodedata')),
            ],
        ),
    ]
