# Generated by Django 4.1.1 on 2022-09-29 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='NodeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VSN', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('gps_lat', models.FloatField()),
                ('gps_lan', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cname', models.CharField(max_length=30)),
                ('labels', models.ManyToManyField(to='ManifestApp.label')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManifestApp.nodedata')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('cname', models.CharField(max_length=30)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManifestApp.nodedata')),
            ],
        ),
        migrations.AddField(
            model_name='nodedata',
            name='tags',
            field=models.ManyToManyField(to='ManifestApp.tag'),
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
                ('hw_model', models.CharField(max_length=30)),
                ('hw_version', models.CharField(max_length=30)),
                ('sw_version', models.CharField(max_length=30)),
                ('datasheet', models.CharField(max_length=30)),
                ('cpu', models.CharField(max_length=30)),
                ('cpu_ram', models.CharField(max_length=30)),
                ('gpu_ram', models.CharField(max_length=30)),
                ('shared_ram', models.CharField(max_length=30)),
                ('capabilities', models.ManyToManyField(to='ManifestApp.capability')),
            ],
        ),
        migrations.CreateModel(
            name='Compute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('hardware_id', models.CharField(max_length=30)),
                ('zone', models.CharField(choices=[('core', 'core'), ('detector', 'detector')], max_length=30)),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManifestApp.hardware')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ManifestApp.nodedata')),
            ],
        ),
    ]
