# Generated by Django 4.1.1 on 2022-09-23 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManifestApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodedata',
            name='tags',
            field=models.ManyToManyField(to='ManifestApp.tag'),
        ),
    ]
