# Generated by Django 4.1.1 on 2022-09-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ManifestApp', '0002_nodedata_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='labels',
            field=models.ManyToManyField(to='ManifestApp.label'),
        ),
    ]
