name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  job1:
    name: Build and test docker images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Start services and perform initial setup
        run:  make start && sleep 10 && make migrate
      - name: Run tests
        run: make test
      - name: Clean up services
        run: make stop
